# Generated by Django 2.2.10 on 2020-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
