# Generated by Django 2.2.10 on 2020-09-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20200914_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.ProductType')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.SubProductType'),
        ),
    ]
