# Generated by Django 2.2.10 on 2020-09-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_auto_20200904_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
