# Generated by Django 2.2.10 on 2020-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_auto_20200914_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproducttype',
            name='name',
            field=models.CharField(default='phone', max_length=50),
        ),
    ]
