# Generated by Django 2.2.10 on 2020-09-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_subproducttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproducttype',
            name='sub_product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproducttypes', to='phones.ProductType'),
        ),
    ]
